services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "webapp-infnet-studies-mngmt"
    #deploy:
    #  replicas: 34
    #  update_config:
    #    parallelism: 2
    #    delay: 10s
    #  restart_policy:
    #    condition: on-failure
    ports:
      - 3000:3000
  database:
    image: mysql:latest
    container_name: "infnet-studies-mngmt-db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: infnet-studies-mngmt-db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"

networks:
  infnet-network:
    driver: overlay