services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "webapp-infnet-studies-mngmt"
    restart: always
    #deploy:
    #  replicas: 34
    #  update_config:
    #    parallelism: 2
    #    delay: 10s
    #  restart_policy:
    #    condition: on-failure
    ports:
      - 80:3000
    networks:
      - infnet-network
  database:
    image: mysql:latest
    container_name: "infnet-studies-mngmt-db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: infnet-studies-mngmt-db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    networks:
      - infnet-network
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - infnet-network
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    networks:
      - infnet-network
networks:
  infnet-network:
    driver: bridge
    #driver: overlay